"""Tests for the CLI diff helpers — parse_outliers, parse_signals, render_diff."""

from youtube_research_agent.cli import parse_outliers, parse_signals, render_diff


SAMPLE_REPORT = """# YouTube content research — algorithmic trading

*Auto-generated by yt-research-agent. 5 briefs ranked by composite score.*

## Signal summary

- **25** videos sampled across **5** seed channels
- **5** outliers detected (≥10× channel baseline)

### Top outliers

| Multiplier | Title | Channel | Views |
|---|---|---|---|
| 23.8× | I Gave ChatGPT $10K to Trade for 30 Days (Real Money) | AI Trading Lab | 1,240,000 |
| 21.9× | I Built an AI Trading Agent From Scratch (Full Code) | Algovibes | 612,000 |
| 18.6× | I built 12 trading algorithms and gave them 6 figures | QuantInsti | 780,000 |

### Top ranked signals

| Composite | Source | Query | Velocity |
|---|---|---|---|
| 0.360 | reddit | I lost $40k in 6 months running an AI trading bot | 1.00 |
| 0.358 | google_trends | ai trading bot | 1.00 |
| 0.358 | google_trends | chatgpt trading strategy | 1.00 |

---

# Briefs
"""


# ---------------------------------------------------------------------------
# parse_outliers
# ---------------------------------------------------------------------------


class TestParseOutliers:
    def test_extracts_all_rows(self):
        rows = parse_outliers(SAMPLE_REPORT)
        assert len(rows) == 3
        assert rows[0]["title"] == "I Gave ChatGPT $10K to Trade for 30 Days (Real Money)"
        assert rows[0]["channel"] == "AI Trading Lab"
        assert rows[0]["multiplier"] == "23.8×"
        assert rows[0]["views"] == "1,240,000"

    def test_returns_empty_when_no_outliers_section(self):
        text = "# Some report\n\n### Other section\n\n| a | b |\n"
        assert parse_outliers(text) == []

    def test_stops_at_next_section(self):
        text = SAMPLE_REPORT  # Top outliers ends at "### Top ranked signals"
        rows = parse_outliers(text)
        # The 3 outlier rows from the outliers section — none from the
        # signals section (which uses a different schema)
        assert len(rows) == 3
        assert all("ChatGPT" in r["title"] or "Algovibes" in r["channel"] or
                   "QuantInsti" in r["channel"] for r in rows)

    def test_handles_infinity_multiplier(self):
        text = """### Top outliers

| Multiplier | Title | Channel | Views |
|---|---|---|---|
| ∞ | Brand new channel breakout | NewCo | 50,000 |
"""
        rows = parse_outliers(text)
        assert len(rows) == 1
        assert rows[0]["multiplier"] == "∞"


# ---------------------------------------------------------------------------
# parse_signals
# ---------------------------------------------------------------------------


class TestParseSignals:
    def test_extracts_all_rows(self):
        rows = parse_signals(SAMPLE_REPORT)
        assert len(rows) == 3
        assert rows[0]["source"] == "reddit"
        assert rows[0]["composite"] == "0.360"
        assert "lost $40k" in rows[0]["query"]
        assert rows[1]["source"] == "google_trends"
        assert rows[1]["query"] == "ai trading bot"

    def test_returns_empty_when_no_section(self):
        text = "### Top outliers\n\n| 10× | t | c | 100 |\n"
        assert parse_signals(text) == []


# ---------------------------------------------------------------------------
# render_diff
# ---------------------------------------------------------------------------


class TestRenderDiff:
    def test_identical_reports_show_no_changes(self):
        out = render_diff(SAMPLE_REPORT, SAMPLE_REPORT)
        assert "# Week-over-week diff" in out
        assert "No new outliers." in out
        assert "No drops since last week." in out
        assert "No new signals." in out

    def test_added_outlier(self):
        new = SAMPLE_REPORT.replace(
            "| 18.6× | I built 12 trading algorithms",
            ("| 50.0× | Brand new breakout video | NewCo | 999,000 |\n"
             "| 18.6× | I built 12 trading algorithms"),
        )
        out = render_diff(SAMPLE_REPORT, new)
        assert "## New outliers (1)" in out
        assert "Brand new breakout video" in out
        assert "## Dropped outliers (0)" in out

    def test_dropped_outlier(self):
        new = SAMPLE_REPORT.replace(
            "| 23.8× | I Gave ChatGPT $10K to Trade for 30 Days (Real Money) | AI Trading Lab | 1,240,000 |\n",
            "",
        )
        out = render_diff(SAMPLE_REPORT, new)
        assert "## Dropped outliers (1)" in out
        assert "I Gave ChatGPT $10K" in out

    def test_added_and_dropped_signal(self):
        new = SAMPLE_REPORT.replace(
            "| 0.358 | google_trends | chatgpt trading strategy",
            "| 0.358 | google_trends | deepseek trading bot",
        )
        out = render_diff(SAMPLE_REPORT, new)
        assert "## New ranked signals (1)" in out
        assert "deepseek trading bot" in out
        assert "## Dropped signals (1)" in out
        assert "chatgpt trading strategy" in out

    def test_diff_output_is_self_contained_markdown(self):
        new = SAMPLE_REPORT.replace("23.8×", "50.0×")    # change one row
        out = render_diff(SAMPLE_REPORT, new)
        # Headings present
        assert out.startswith("# Week-over-week diff")
        # All 4 sections present
        for header in ["New outliers", "Dropped outliers",
                       "New ranked signals", "Dropped signals"]:
            assert f"## {header}" in out
